### ISSUE TITLE
[Bug] Unidentified ad example

### ISSUE THREAD

**Issue by Hebo** [DrKain/subclean#14]
Hey, great package, been working really well. Saw an ad that didn't get picked up just now:

```
46
00:01:58,900 --> 00:02:04,974
Watch Movies, TV Series & Live Sports
www.admitme.app
```

Anecdotally, I see a lot of ads in a similar format, wonder if it's worth having a regex to detect the format of URLs, as they're likely an ad (or at least .app)?

**Comment by DrKain** [comment]
Hi, thanks for reporting. I'll add `admitme.app` to the filters.  

A filter for all URLs would need to be optional, seeing as there are plenty of instances where a character is taking about a certain website or domain that may not be an ad
