### ISSUE TITLE
[Feature Request] switch to show deleted line

### ISSUE THREAD

**Issue by Irek7** [DrKain/subclean#25]
hi 
I tried to use --debug but it doesn't show what exactly is being deleted. would be nice to have switch to show what exactly is gonna be deleted.

Irek

**Comment by DrKain** [comment]
What more information do you require? When using `--debug` the line, node # and filter matched will be logged.

```
[Match] Advertising found in node 901 (/^sync(ed|) (and|&) correct(ed|ion) by/)
[Line] synced and corrected by Some Username
```

https://github.com/DrKain/subclean/blob/main/src/index.ts#L350

**Comment by Irek7** [comment]
sorry, my bad. I just written alias for it and forgot to add Line into grep. its perfect as it is now.
